//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diet
    {
        public string UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> Dairy { get; set; }
        public Nullable<int> Fruit { get; set; }
        public Nullable<int> Carbohidrate { get; set; }
        public Nullable<int> Protein { get; set; }
        public Nullable<int> Vegetable { get; set; }
        public Nullable<int> Fat { get; set; }
        public Nullable<int> Sugar { get; set; }
        public Nullable<int> Water { get; set; }
    }
}
